# This is a basic workflow to help you get start with Actions

name: CI
...
  steps:
    # check out repo under $github workspace
    - uses: actions/checkout@2
    # run shellcheck
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
